include: package:extra_pedantic/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    always_put_required_named_parameters_first: ignore
    close_sinks: ignore