name: goactive
description: An example of mobile application developed with Flutter by Anna Domashych
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  extra_pedantic: ^1.2.0

flutter:
  uses-material-design: true