name: goactive
description: An example of mobile application developed with Flutter by Anna Domashych
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^4.0.2
  injectable: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  extra_pedantic: ^1.2.0
  freezed: ^0.10.7
  injectable_generator: ^0.3.4
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true