name: goactive
description: An example of mobile application developed with Flutter by Anna Domashych
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^0.5.0
  cached_network_image: ^2.2.0+1
  get_it: ^4.0.2
  i69n: ^1.1.0
  injectable: ^0.4.0
  intl: ^0.16.1
  flutter_bloc: ^4.0.0
  shimmer: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.5.0
  build_runner:
  extra_pedantic: ^1.2.0
  flutter_launcher_name: ^0.0.1
  freezed: ^0.10.9
  injectable_generator: ^0.4.0
  json_serializable: ^3.3.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true

flutter_launcher_name:
  name: "GoActive!"